FROM python:3.10.0

WORKDIR /app

COPY requirements.txt requirements.txt

RUN pip install --upgrade pip

RUN pip install -r requirements.txt

COPY . .

EXPOSE 5000

RUN celery -A manila.celery worker --loglevel=info --detach

CMD ["python", "manila/app.py"]